FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
COPY yarn.lock ./

ARG VITE_SERVER_PORT
ARG JWT_SECRET

ENV VITE_SERVER_PORT=$VITE_SERVER_PORT
ENV JWT_SECRET=$JWT_SECRET

RUN yarn install

COPY server.js ./
COPY data/ ./data/

EXPOSE $VITE_SERVER_PORT

CMD ["node", "server.js"]
